project:
  type: book
  output-dir: "_book"

book:
  output-file: "proposal"
  title: |
    Modulation of the Immune Response to Influenza Vaccination by Host and
    Vaccine Characteristics
  subtitle: |
    Dissertation proposal by
  author: "W. Zane Billings"
  date: "2023-04-06"
  date-format: iso
  chapters:
    - index.qmd
    - aims.qmd
    - significance.qmd
    - approach.qmd
    - references.qmd

#bibliography: references.bib

format:
  docx:
    reference-doc: template.docx
    toc: false
    bibliography: references.bib
    csl: aje.csl
