---
format: gfm
---

<!-- This document is generated by NOTES.qmd Edit that instead. -->

# Amanda's project and Sarah Cobey meeting thoughts

* To what extent can I do a follow-up of Amanda's project? How soon are you
confident that I would be able to start working on it?

* Sarah Cobey's question -- what if we do a subgroup analysis on people with
strong responses? Do we see different trends in Ag landscapes? Are there
distinct boosts? Do you plan to address this as part of Amanda's paper?
If not, would it be a good aim idea?

* John Tsang and Ben Cowling points -- how do we interpret slope vs intercept
of the line? In some ways, AUC means that a person with a flat, constantly low
(but nonzero) Ag landscape can be the same as someone with a steeply sloped
pattern. Intercept as a measure of "overall magnitude" (it measures the
magnitude of the response to the homologous strain), and then slope measures
breadth in some sense. If the x values are centered about the mean, then the
slope and intercept are independent.

Cov(b0, b1) = -sigma^2 * (xbar / Sxx) and xbar = 0 if x is centered.

* I don't really understand the normalized vs unnormalized AUC slopes? The
  slope of the normalized line will be (normalizing factor) * (original slope).
  (Video time stamp around 30 minutes)
  
* How, if at all, should Amanda's next steps fit into my proposal?
  
* Sarah Cobey -- there is longitudinal structure in the data, should
  we incorporate this in our model? How would we do that? Do this fit into my
  aim of using the Ag distance in a model similar to Yang's?
  
  - Incorporating clusters from individuals
  
  - Breadth within individuals? Doesn't seem like high responders always had
    high breadth. Maybe this fits into clustering project?

* Ben: should the breadth be two directional? Seems like we should expect
people to respond better to historical strains than to new strains.

## Potential papers for proposal

* Antigenic distance modeling paper compliment to yang's strain-specific models

* Paper comparing veronika's model predictions with our data

* Paper using DIVERsity data to examine the effect of different vaccines and
determining if we see the same host demographic patterns across the 
different data sets

* Paper exploring summary metrics for antigenic landscapes What if we use
3d landscapes? How does use the slope/intercept compare to the AUC that
we are using in Amanda's paper?

* Paper comparing Andrea Sant's data with Ted's data. We see the same 
patterns with t cells that we see with antibodies which implies that
perhaps there is an underlying mechanism and the reason isn't just steric
hindrance.
